import { Geist, Geist_Mono, Nanum_Gothic_Coding } from 'next/font/google';
import { TooltipProvider } from '@/components/common/ui/tooltip';
import { Providers } from './providers';
import './globals.css';

const nanumGothicCoding = Nanum_Gothic_Coding({
  variable: '--font-nanum-gothic-coding',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nanumGothicCoding.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  const savedTheme = localStorage.getItem("theme");
                  const systemDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

                  document.documentElement.classList.toggle(
                    "dark",
                    savedTheme === "dark" || (!savedTheme && systemDark)
                  );
                } catch (e) {}
              })();
            `,
          }}
        />
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
        </Providers>
      </body>
    </html>
  );
}
